on:
  push:
  workflow_dispatch:

jobs:
  lint:
    name: Lint policies
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2.2.0
        with:
          version: 0.61

      - name: Setup Regal
        uses: StyraInc/setup-regal@v1.0.0
        with:
          version: 0.21

      - name: OPA Check
        if: ${{ !cancelled() }}
        run: find . -maxdepth 1 -type f -name '*.rego' -print0 | xargs -0L1 opa check --strict --max-errors 0

      - name: Regal Lint
        if: ${{ !cancelled() }}
        run: regal lint --format github .

  deploy:
    name: Deploy policies
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: lint
    if: success() && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Upload
        env:
          PHYLUM_TOKEN: ${{ secrets.PHYLUM_TOKEN }}
        run: python3 .github/workflows/upload.py
